# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a3d0933a5f78a6d5f6a40282cd9dc78677ab8c326dfdb71b195eb421ce201d44dded7674fc864dec33d63ce9d4614b04b9fb42c9bb10137019dda9b69b57ff

test:
  secret_key_base: 5108d561512eb380dd6a8486ffa677d0f16ecc3a6c7046b1f791f8d6ba21dd180a31ad1345e8ca64bdf3bf6a87d1813f5f42819884d8596bef0a7d7f24f9b3b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
