# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35075e1c69c529c1ecfae39d8b2ae40eb23e99a8de93163c4d9169d3a42d3647932f1aec6b309639c7331a8c31588820386957a4c09b2969892504757bfcb34d

test:
  secret_key_base: de5f21b58b656d905ea8b3f42f7e5961b9be58f46447c115c78695457833aecd86c2ac3b0eb19852eb9de41307375e83623ff63da0f7792a9f592c24eb4966ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
