# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a71f4b17bf0ccc9b8586efacdfe741f124dbebfd919289e946ea9fd904904e89aa5eba05064523eb8b9ceae34e4965bb63e33a26d018323726ebd98ef6065ba9

test:
  secret_key_base: c1a142d9dd63480a77c2f3b20695a6fe65247d04152424477d11b4ed0df6ba76701325326e5c3c5d80b3d7d3731512d9724586c93e51a2a96a0946e4d531704c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
