# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7df7186a394e3d968a34d8ef6a85d0689b95052b8fbecdb3e0fafc42598778b7ba069e5b507e15e8c7082271cf0f4328fd1674964c49709caa04140433208a81

test:
  secret_key_base: 8a40f364d4a407d94289958f1191ce96e3e13203578ddf868ded776c340119a0a959264a4e8eb8eaeca3b7bcf2c15775a82fac67ffcba9bf0e0ad1b201a1b1ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
