# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b19f2068f03d91c0573bec0ae16369a9d1723df2b9f7456fe1602b15696e7d60213400778784e34f3f3019be68f9573646f2b27c566a397f43c1280a56f396b0

test:
  secret_key_base: 34a649275841e2a0d18e6b0a002f4cb1dfdc20b4762ee19fa9a032b4a5df2f3fb4abc59bc5639458001c4e28408e0752da1c0e4e251631d7050c03f8c2cac9b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
