# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b24f5e5e0406c4a16d152e9f60369c24f671e2c8be06100076781eec3874bd76649eac91d5636799b88672729d0700978a9f4415675cd156c5175aa3482defa

test:
  secret_key_base: cb1eb46d5beffaf8e5c1c0553ac374519e49f1784bbef98280a092a518c63f3b88ed1b8b56190f27d25f9380ef77bc53829e84997bbc994a863d4c5628904213

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
