# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab932b8ef019ba18c410e273399f79268538124bf5efbdfc0d1b5a4d13490969fd439223ff5afb5a6ef136984db9e51ab8192d6a6e5c6c6c146b566941cf8989

test:
  secret_key_base: 7ff5cec54e5c972d3569c532df233ac1b930a460711730ee1443a6fe6ad427f27e343c126bf492ab947ca6f687ba4f6ff24eaa6221ef91e4f1825dcb3877bcf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
