# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56de975b1253fbced8efe9f05640e709c13b010719b22a1128961a63e841b0f4701fc1f66571f7c9450bd62e3592ebca02b98fc200b2803a726d8ae272e8de8b

test:
  secret_key_base: 1cfb5b50660f2490f7c2da7fa38ab69c82e5a62e51e7634e08792ed292428ba11ad6bb4223f34e8704ff4fc25da9a3db407bb036aee0246fc488dba5630f9201

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
